openapi: 3.0.1
info:
  title: Petrolifera API
  version: v1
servers:
- url: /
security:
- Bearer:
  - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3JmcGZpbGlwZUBnbWFpbC5jb20iLCJuYmYiOjE2MTY1ODQ3OTcsImV4cCI6MTYyMzc4NDc5MywiaWF0IjoxNjE2NTg0Nzk3LCJwYXlsb2FkIjp7IklEIjoyMDA1OCwiVXNlck5hbWUiOm51bGwsIkNvZGVfdXNlciI6MCwiSWRUaXBvUGVyZmlsIjoyOSwiUGVyZmlsIjoicGVkcm8iLCJOb21lIjoicGVkcm8iLCJOSUYiOjEyMzIxMzIxMjIsIkVtYWlsIjoic3JmcGZpbGlwZUBnbWFpbC5jb20iLCJUZWxlZm9uZSI6bnVsbCwiTW9yYWRhIjoiIiwiQ29kaWdvUG9zdGFsIjoiMzcyMCIsIkxvY2FsaWRhZGUiOiJhc2dkZ2FoZ2RhIiwiTnVtZXJvTWVjYW5vZ3JhZmljbyI6MTIzNDUsIkVzY29sYSI6IiIsIlNpZ2xhRXNjb2xhIjpudWxsLCJJZEVzY29sYSI6MCwiQ3Vyc28iOiIiLCJJZEN1cnNvIjowfX0.Z7EJk4C74_mY8wXR54goxcOCr6L1AeIscBOrS8blPko
paths:
  /Gvms/Gvm/GetGvm:
    get:
      parameters:
      - explode: true
        in: query
        name: identificadorPI
        required: false
        schema:
          nullable: true
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GvmDTOResultado'
            application/json:
              schema:
                $ref: '#/components/schemas/GvmDTOResultado'
            text/json:
              schema:
                $ref: '#/components/schemas/GvmDTOResultado'
          description: Success
      tags:
      - Gvm
  /Gvms/Gvm/Login:
    post:
      parameters:
      - explode: true
        in: query
        name: idendificadorPi
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: password
        required: false
        schema:
          nullable: true
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StringResultado'
            application/json:
              schema:
                $ref: '#/components/schemas/StringResultado'
            text/json:
              schema:
                $ref: '#/components/schemas/StringResultado'
          description: Success
      tags:
      - Gvm
  /Gvms/Gvm/RegistarRaspberryPi:
    post:
      parameters:
      - explode: true
        in: query
        name: identificador
        required: false
        schema:
          nullable: true
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Resultado'
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
            text/json:
              schema:
                $ref: '#/components/schemas/Resultado'
          description: Success
      tags:
      - Gvm
  /Gvms/Gvm/RegistarEvento:
    post:
      parameters:
      - explode: true
        in: query
        name: tipoEvento
        required: false
        schema:
          $ref: '#/components/schemas/TiposTipoEvento'
        style: form
      - explode: true
        in: query
        name: msg
        required: false
        schema:
          default: ""
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: refCompartimento
        required: false
        schema:
          format: int64
          nullable: true
          type: integer
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Resultado'
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
            text/json:
              schema:
                $ref: '#/components/schemas/Resultado'
          description: Success
      tags:
      - Gvm
  /Gvms/Gvm/GetVenda:
    get:
      parameters:
      - explode: true
        in: query
        name: tokenVenda
        required: false
        schema:
          nullable: true
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CustomVendaResultado'
            application/json:
              schema:
                $ref: '#/components/schemas/CustomVendaResultado'
            text/json:
              schema:
                $ref: '#/components/schemas/CustomVendaResultado'
          description: Success
      tags:
      - Gvm
  /Gvms/Gvm/FinalizarVenda:
    get:
      parameters:
      - explode: true
        in: query
        name: refVenda
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - explode: true
        in: query
        name: refCompartimentoProduto
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - explode: true
        in: query
        name: refCompartimentoVasilhame
        required: false
        schema:
          format: int64
          nullable: true
          type: integer
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Resultado'
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
            text/json:
              schema:
                $ref: '#/components/schemas/Resultado'
          description: Success
      tags:
      - Gvm
  /Gvms/Gvm/DownloadImage:
    get:
      parameters:
      - explode: true
        in: query
        name: refProduto
        required: false
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          description: Success
      tags:
      - Gvm
  /Gvms/Gvm/AlterarEstado:
    post:
      parameters:
      - explode: true
        in: query
        name: refCompartimento
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - explode: true
        in: query
        name: estado
        required: false
        schema:
          $ref: '#/components/schemas/EstadosCompartimentoEstado'
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Resultado'
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
            text/json:
              schema:
                $ref: '#/components/schemas/Resultado'
          description: Success
      tags:
      - Gvm
  /Gvms/OrdemServico/AbrirOrdemServico:
    get:
      parameters:
      - explode: true
        in: query
        name: token
        required: false
        schema:
          nullable: true
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AberturaOrdemServicoResultado'
            application/json:
              schema:
                $ref: '#/components/schemas/AberturaOrdemServicoResultado'
            text/json:
              schema:
                $ref: '#/components/schemas/AberturaOrdemServicoResultado'
          description: Success
      tags:
      - OrdemServico
  /Gvms/OrdemServico/Recolha:
    post:
      parameters:
      - explode: true
        in: query
        name: refOrdemSercico
        required: false
        schema:
          format: int64
          type: integer
        style: form
      requestBody:
        content:
          application/json-patch+json:
            schema:
              items:
                format: int64
                type: integer
              nullable: true
              type: array
          application/json:
            schema:
              items:
                format: int64
                type: integer
              nullable: true
              type: array
          text/json:
            schema:
              items:
                format: int64
                type: integer
              nullable: true
              type: array
          application/*+json:
            schema:
              items:
                format: int64
                type: integer
              nullable: true
              type: array
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Resultado'
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
            text/json:
              schema:
                $ref: '#/components/schemas/Resultado'
          description: Success
      tags:
      - OrdemServico
  /Gvms/OrdemServico/Deposito:
    post:
      parameters:
      - explode: true
        in: query
        name: refOrdemServico
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - explode: true
        in: query
        name: refCompartimento
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - explode: true
        in: query
        name: refProduto
        required: false
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Resultado'
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
            text/json:
              schema:
                $ref: '#/components/schemas/Resultado'
          description: Success
      tags:
      - OrdemServico
  /Gvms/OrdemServico/FinalizarOrdemServico:
    post:
      parameters:
      - explode: true
        in: query
        name: refOrdemSercico
        required: false
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Resultado'
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
            text/json:
              schema:
                $ref: '#/components/schemas/Resultado'
          description: Success
      tags:
      - OrdemServico
  /Petroliferas/Petrolifera/CriarVenda:
    post:
      requestBody:
        content:
          application/json-patch+json:
            schema:
              items:
                $ref: '#/components/schemas/VendaPetrolifera'
              nullable: true
              type: array
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/VendaPetrolifera'
              nullable: true
              type: array
          text/json:
            schema:
              items:
                $ref: '#/components/schemas/VendaPetrolifera'
              nullable: true
              type: array
          application/*+json:
            schema:
              items:
                $ref: '#/components/schemas/VendaPetrolifera'
              nullable: true
              type: array
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/VendaPetroliferaListResultado'
            application/json:
              schema:
                $ref: '#/components/schemas/VendaPetroliferaListResultado'
            text/json:
              schema:
                $ref: '#/components/schemas/VendaPetroliferaListResultado'
          description: Success
      tags:
      - Petrolifera
  /Petroliferas/Petrolifera/AnularVenda:
    post:
      parameters:
      - explode: true
        in: query
        name: token
        required: false
        schema:
          nullable: true
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Resultado'
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
            text/json:
              schema:
                $ref: '#/components/schemas/Resultado'
          description: Success
      tags:
      - Petrolifera
  /Petroliferas/Petrolifera/GetGvms:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GvmDTOListResultado'
            application/json:
              schema:
                $ref: '#/components/schemas/GvmDTOListResultado'
            text/json:
              schema:
                $ref: '#/components/schemas/GvmDTOListResultado'
          description: Success
      tags:
      - Petrolifera
  /Petroliferas/Petrolifera/GetProdutosByTipo:
    get:
      parameters:
      - explode: true
        in: query
        name: tipo
        required: false
        schema:
          $ref: '#/components/schemas/TipoProduto'
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProdutoDTOListResultado'
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoDTOListResultado'
            text/json:
              schema:
                $ref: '#/components/schemas/ProdutoDTOListResultado'
          description: Success
      tags:
      - Petrolifera
  /Petroliferas/Petrolifera/GetProdutos:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProdutoDTOListResultado'
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoDTOListResultado'
            text/json:
              schema:
                $ref: '#/components/schemas/ProdutoDTOListResultado'
          description: Success
      tags:
      - Petrolifera
  /Petroliferas/Petrolifera/GetProdutoDetalhe:
    get:
      parameters:
      - explode: true
        in: query
        name: refProduto
        required: false
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProdutoDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/ProdutoDTO'
          description: Success
      tags:
      - Petrolifera
  /Petroliferas/Petrolifera/GetLocais:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/LocalDTOListResultado'
            application/json:
              schema:
                $ref: '#/components/schemas/LocalDTOListResultado'
            text/json:
              schema:
                $ref: '#/components/schemas/LocalDTOListResultado'
          description: Success
      tags:
      - Petrolifera
  /Petroliferas/Petrolifera/GetDetalheLocal:
    get:
      parameters:
      - explode: true
        in: query
        name: refProduto
        required: false
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/LocalDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/LocalDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/LocalDTO'
          description: Success
      tags:
      - Petrolifera
  /Petroliferas/Petrolifera/DownloadImage:
    get:
      parameters:
      - explode: true
        in: query
        name: refImagem
        required: false
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          description: Success
      tags:
      - Petrolifera
components:
  schemas:
    TipoCompartimento:
      enum:
      - 0
      - 1
      format: int32
      type: integer
    FechaduraDTO:
      additionalProperties: false
      example:
        endereco: endereco
        id: 1
        canal: 5
      properties:
        id:
          format: int64
          type: integer
        endereco:
          maxLength: 10
          minLength: 0
          nullable: true
          type: string
        canal:
          format: int32
          nullable: true
          type: integer
      type: object
    LedDTO:
      additionalProperties: false
      example:
        address: address
        channel: 2
        start: 7
        end: 9
        id: 5
      properties:
        id:
          format: int64
          type: integer
        address:
          nullable: true
          type: string
        channel:
          format: int32
          nullable: true
          type: integer
        start:
          format: int32
          nullable: true
          type: integer
        end:
          format: int32
          nullable: true
          type: integer
      type: object
    CompartimentoDTO:
      additionalProperties: false
      example:
        ativo: true
        numero: numero
        leds:
        - address: address
          channel: 2
          start: 7
          end: 9
          id: 5
        - address: address
          channel: 2
          start: 7
          end: 9
          id: 5
        id: 6
        fechaduras:
        - endereco: endereco
          id: 1
          canal: 5
        - endereco: endereco
          id: 1
          canal: 5
      properties:
        id:
          format: int64
          type: integer
        numero:
          maxLength: 10
          minLength: 0
          nullable: true
          type: string
        tipo:
          $ref: '#/components/schemas/TipoCompartimento'
        ativo:
          type: boolean
        fechaduras:
          items:
            $ref: '#/components/schemas/FechaduraDTO'
          nullable: true
          type: array
        leds:
          items:
            $ref: '#/components/schemas/LedDTO'
          nullable: true
          type: array
      type: object
    GvmDTO:
      additionalProperties: false
      example:
        compartimentos:
        - ativo: true
          numero: numero
          leds:
          - address: address
            channel: 2
            start: 7
            end: 9
            id: 5
          - address: address
            channel: 2
            start: 7
            end: 9
            id: 5
          id: 6
          fechaduras:
          - endereco: endereco
            id: 1
            canal: 5
          - endereco: endereco
            id: 1
            canal: 5
        - ativo: true
          numero: numero
          leds:
          - address: address
            channel: 2
            start: 7
            end: 9
            id: 5
          - address: address
            channel: 2
            start: 7
            end: 9
            id: 5
          id: 6
          fechaduras:
          - endereco: endereco
            id: 1
            canal: 5
          - endereco: endereco
            id: 1
            canal: 5
        id: 0
      properties:
        id:
          format: int64
          type: integer
        compartimentos:
          items:
            $ref: '#/components/schemas/CompartimentoDTO'
          nullable: true
          type: array
      type: object
    GvmDTOResultado:
      additionalProperties: false
      example:
        ok: true
        message: message
        value:
          compartimentos:
          - ativo: true
            numero: numero
            leds:
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            id: 6
            fechaduras:
            - endereco: endereco
              id: 1
              canal: 5
            - endereco: endereco
              id: 1
              canal: 5
          - ativo: true
            numero: numero
            leds:
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            id: 6
            fechaduras:
            - endereco: endereco
              id: 1
              canal: 5
            - endereco: endereco
              id: 1
              canal: 5
          id: 0
      properties:
        ok:
          type: boolean
        message:
          nullable: true
          type: string
        value:
          $ref: '#/components/schemas/GvmDTO'
      type: object
    StringResultado:
      additionalProperties: false
      example:
        ok: true
        message: message
        value: value
      properties:
        ok:
          type: boolean
        message:
          nullable: true
          type: string
        value:
          nullable: true
          type: string
      type: object
    Resultado:
      additionalProperties: false
      example:
        ok: true
        message: message
      properties:
        ok:
          type: boolean
        message:
          nullable: true
          type: string
      type: object
    TiposTipoEvento:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      format: int32
      type: integer
    TipoProduto:
      enum:
      - 0
      - 1
      format: int32
      type: integer
    ProdutoVM:
      additionalProperties: false
      example:
        preco: 1.4658129805029452
        dimensoes: dimensoes
        refEntidade: 6
        presoTotal: presoTotal
        nome: nome
        id: 0
        refImagem: 5
        descricao: descricao
        pesoLiquido: pesoLiquido
      properties:
        id:
          format: int64
          nullable: true
          type: integer
        nome:
          nullable: true
          type: string
        refEntidade:
          format: int64
          nullable: true
          type: integer
        tipo:
          $ref: '#/components/schemas/TipoProduto'
        descricao:
          nullable: true
          type: string
        preco:
          format: double
          nullable: true
          type: number
        presoTotal:
          nullable: true
          type: string
        pesoLiquido:
          nullable: true
          type: string
        dimensoes:
          nullable: true
          type: string
        refImagem:
          format: int64
          nullable: true
          type: integer
      type: object
    GvmVM:
      additionalProperties: false
      example:
        numeroSerie: numeroSerie
        refNo: 7
        refEntidade: 2
        refLocal: 5
        versaoSoftware: versaoSoftware
        ultimaComunicacao: 2000-01-23T04:56:07.000+00:00
        latitude: latitude
        nome: nome
        dataProducao: 2000-01-23T04:56:07.000+00:00
        versaoFirmware: versaoFirmware
        modelo: modelo
        longitude: longitude
      properties:
        nome:
          nullable: true
          type: string
        modelo:
          nullable: true
          type: string
        numeroSerie:
          nullable: true
          type: string
        dataProducao:
          format: date-time
          nullable: true
          type: string
        versaoFirmware:
          nullable: true
          type: string
        versaoSoftware:
          nullable: true
          type: string
        ultimaComunicacao:
          format: date-time
          nullable: true
          type: string
        refLocal:
          format: int64
          nullable: true
          type: integer
        refEntidade:
          format: int64
          nullable: true
          type: integer
        refNo:
          format: int64
          nullable: true
          type: integer
        latitude:
          nullable: true
          type: string
        longitude:
          nullable: true
          type: string
      type: object
    CustomVenda:
      additionalProperties: false
      example:
        refCompartimentoProduto: 9
        produto:
          preco: 1.4658129805029452
          dimensoes: dimensoes
          refEntidade: 6
          presoTotal: presoTotal
          nome: nome
          id: 0
          refImagem: 5
          descricao: descricao
          pesoLiquido: pesoLiquido
        vasilhame: true
        refCompartimentoVasilhame: 3
        gvm:
          numeroSerie: numeroSerie
          refNo: 7
          refEntidade: 2
          refLocal: 5
          versaoSoftware: versaoSoftware
          ultimaComunicacao: 2000-01-23T04:56:07.000+00:00
          latitude: latitude
          nome: nome
          dataProducao: 2000-01-23T04:56:07.000+00:00
          versaoFirmware: versaoFirmware
          modelo: modelo
          longitude: longitude
      properties:
        produto:
          $ref: '#/components/schemas/ProdutoVM'
        gvm:
          $ref: '#/components/schemas/GvmVM'
        vasilhame:
          nullable: true
          type: boolean
        refCompartimentoProduto:
          format: int64
          nullable: true
          type: integer
        refCompartimentoVasilhame:
          format: int64
          nullable: true
          type: integer
      type: object
    CustomVendaResultado:
      additionalProperties: false
      example:
        ok: true
        message: message
        value:
          refCompartimentoProduto: 9
          produto:
            preco: 1.4658129805029452
            dimensoes: dimensoes
            refEntidade: 6
            presoTotal: presoTotal
            nome: nome
            id: 0
            refImagem: 5
            descricao: descricao
            pesoLiquido: pesoLiquido
          vasilhame: true
          refCompartimentoVasilhame: 3
          gvm:
            numeroSerie: numeroSerie
            refNo: 7
            refEntidade: 2
            refLocal: 5
            versaoSoftware: versaoSoftware
            ultimaComunicacao: 2000-01-23T04:56:07.000+00:00
            latitude: latitude
            nome: nome
            dataProducao: 2000-01-23T04:56:07.000+00:00
            versaoFirmware: versaoFirmware
            modelo: modelo
            longitude: longitude
      properties:
        ok:
          type: boolean
        message:
          nullable: true
          type: string
        value:
          $ref: '#/components/schemas/CustomVenda'
      type: object
    EstadosCompartimentoEstado:
      enum:
      - 0
      - 1
      - 2
      format: int32
      type: integer
    CompartimentoVM:
      additionalProperties: false
      example:
        ativo: true
        livreSemProduto: true
        numero: numero
        refProduto: 5
        vasilhame: true
        troca: true
        id: 6
        refGvm: 1
        compartimentoBloqueado: true
      properties:
        id:
          format: int64
          nullable: true
          type: integer
        numero:
          nullable: true
          type: string
        tipo:
          $ref: '#/components/schemas/TipoCompartimento'
        ativo:
          nullable: true
          type: boolean
        refGvm:
          format: int64
          nullable: true
          type: integer
        refProduto:
          format: int64
          nullable: true
          type: integer
        livreSemProduto:
          type: boolean
        compartimentoBloqueado:
          type: boolean
        vasilhame:
          type: boolean
        troca:
          type: boolean
      type: object
    OSCompartimentoProduto:
      additionalProperties: false
      example:
        produto:
          preco: 1.4658129805029452
          dimensoes: dimensoes
          refEntidade: 6
          presoTotal: presoTotal
          nome: nome
          id: 0
          refImagem: 5
          descricao: descricao
          pesoLiquido: pesoLiquido
        ocupado: true
        compartimento:
          ativo: true
          livreSemProduto: true
          numero: numero
          refProduto: 5
          vasilhame: true
          troca: true
          id: 6
          refGvm: 1
          compartimentoBloqueado: true
      properties:
        compartimento:
          $ref: '#/components/schemas/CompartimentoVM'
        produto:
          $ref: '#/components/schemas/ProdutoVM'
        ocupado:
          type: boolean
      type: object
    AberturaOrdemServico:
      additionalProperties: false
      example:
        listaRecolha:
        - produto:
            preco: 1.4658129805029452
            dimensoes: dimensoes
            refEntidade: 6
            presoTotal: presoTotal
            nome: nome
            id: 0
            refImagem: 5
            descricao: descricao
            pesoLiquido: pesoLiquido
          ocupado: true
          compartimento:
            ativo: true
            livreSemProduto: true
            numero: numero
            refProduto: 5
            vasilhame: true
            troca: true
            id: 6
            refGvm: 1
            compartimentoBloqueado: true
        - produto:
            preco: 1.4658129805029452
            dimensoes: dimensoes
            refEntidade: 6
            presoTotal: presoTotal
            nome: nome
            id: 0
            refImagem: 5
            descricao: descricao
            pesoLiquido: pesoLiquido
          ocupado: true
          compartimento:
            ativo: true
            livreSemProduto: true
            numero: numero
            refProduto: 5
            vasilhame: true
            troca: true
            id: 6
            refGvm: 1
            compartimentoBloqueado: true
        refOrdemServico: 0
        listaDeposito:
        - produto:
            preco: 1.4658129805029452
            dimensoes: dimensoes
            refEntidade: 6
            presoTotal: presoTotal
            nome: nome
            id: 0
            refImagem: 5
            descricao: descricao
            pesoLiquido: pesoLiquido
          ocupado: true
          compartimento:
            ativo: true
            livreSemProduto: true
            numero: numero
            refProduto: 5
            vasilhame: true
            troca: true
            id: 6
            refGvm: 1
            compartimentoBloqueado: true
        - produto:
            preco: 1.4658129805029452
            dimensoes: dimensoes
            refEntidade: 6
            presoTotal: presoTotal
            nome: nome
            id: 0
            refImagem: 5
            descricao: descricao
            pesoLiquido: pesoLiquido
          ocupado: true
          compartimento:
            ativo: true
            livreSemProduto: true
            numero: numero
            refProduto: 5
            vasilhame: true
            troca: true
            id: 6
            refGvm: 1
            compartimentoBloqueado: true
      properties:
        refOrdemServico:
          format: int64
          nullable: true
          type: integer
        listaRecolha:
          items:
            $ref: '#/components/schemas/OSCompartimentoProduto'
          nullable: true
          type: array
        listaDeposito:
          items:
            $ref: '#/components/schemas/OSCompartimentoProduto'
          nullable: true
          type: array
      type: object
    AberturaOrdemServicoResultado:
      additionalProperties: false
      example:
        ok: true
        message: message
        value:
          listaRecolha:
          - produto:
              preco: 1.4658129805029452
              dimensoes: dimensoes
              refEntidade: 6
              presoTotal: presoTotal
              nome: nome
              id: 0
              refImagem: 5
              descricao: descricao
              pesoLiquido: pesoLiquido
            ocupado: true
            compartimento:
              ativo: true
              livreSemProduto: true
              numero: numero
              refProduto: 5
              vasilhame: true
              troca: true
              id: 6
              refGvm: 1
              compartimentoBloqueado: true
          - produto:
              preco: 1.4658129805029452
              dimensoes: dimensoes
              refEntidade: 6
              presoTotal: presoTotal
              nome: nome
              id: 0
              refImagem: 5
              descricao: descricao
              pesoLiquido: pesoLiquido
            ocupado: true
            compartimento:
              ativo: true
              livreSemProduto: true
              numero: numero
              refProduto: 5
              vasilhame: true
              troca: true
              id: 6
              refGvm: 1
              compartimentoBloqueado: true
          refOrdemServico: 0
          listaDeposito:
          - produto:
              preco: 1.4658129805029452
              dimensoes: dimensoes
              refEntidade: 6
              presoTotal: presoTotal
              nome: nome
              id: 0
              refImagem: 5
              descricao: descricao
              pesoLiquido: pesoLiquido
            ocupado: true
            compartimento:
              ativo: true
              livreSemProduto: true
              numero: numero
              refProduto: 5
              vasilhame: true
              troca: true
              id: 6
              refGvm: 1
              compartimentoBloqueado: true
          - produto:
              preco: 1.4658129805029452
              dimensoes: dimensoes
              refEntidade: 6
              presoTotal: presoTotal
              nome: nome
              id: 0
              refImagem: 5
              descricao: descricao
              pesoLiquido: pesoLiquido
            ocupado: true
            compartimento:
              ativo: true
              livreSemProduto: true
              numero: numero
              refProduto: 5
              vasilhame: true
              troca: true
              id: 6
              refGvm: 1
              compartimentoBloqueado: true
      properties:
        ok:
          type: boolean
        message:
          nullable: true
          type: string
        value:
          $ref: '#/components/schemas/AberturaOrdemServico'
      type: object
    TipoOrigem:
      enum:
      - 0
      - 1
      format: int32
      type: integer
    VendaPetrolifera:
      additionalProperties: false
      example:
        refProduto: 6
        vasilhame: true
        guid: guid
        refGvm: 0
      properties:
        refGvm:
          format: int64
          nullable: true
          type: integer
        refProduto:
          format: int64
          nullable: true
          type: integer
        vasilhame:
          type: boolean
        guid:
          nullable: true
          type: string
        origem:
          $ref: '#/components/schemas/TipoOrigem'
      type: object
    VendaPetroliferaListResultado:
      additionalProperties: false
      example:
        ok: true
        message: message
        value:
        - refProduto: 6
          vasilhame: true
          guid: guid
          refGvm: 0
        - refProduto: 6
          vasilhame: true
          guid: guid
          refGvm: 0
      properties:
        ok:
          type: boolean
        message:
          nullable: true
          type: string
        value:
          items:
            $ref: '#/components/schemas/VendaPetrolifera'
          nullable: true
          type: array
      type: object
    GvmDTOListResultado:
      additionalProperties: false
      example:
        ok: true
        message: message
        value:
        - compartimentos:
          - ativo: true
            numero: numero
            leds:
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            id: 6
            fechaduras:
            - endereco: endereco
              id: 1
              canal: 5
            - endereco: endereco
              id: 1
              canal: 5
          - ativo: true
            numero: numero
            leds:
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            id: 6
            fechaduras:
            - endereco: endereco
              id: 1
              canal: 5
            - endereco: endereco
              id: 1
              canal: 5
          id: 0
        - compartimentos:
          - ativo: true
            numero: numero
            leds:
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            id: 6
            fechaduras:
            - endereco: endereco
              id: 1
              canal: 5
            - endereco: endereco
              id: 1
              canal: 5
          - ativo: true
            numero: numero
            leds:
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            - address: address
              channel: 2
              start: 7
              end: 9
              id: 5
            id: 6
            fechaduras:
            - endereco: endereco
              id: 1
              canal: 5
            - endereco: endereco
              id: 1
              canal: 5
          id: 0
      properties:
        ok:
          type: boolean
        message:
          nullable: true
          type: string
        value:
          items:
            $ref: '#/components/schemas/GvmDTO'
          nullable: true
          type: array
      type: object
    ProdutoDTO:
      additionalProperties: false
      example:
        preco: 1.4658129805029452
        dimensoes: dimensoes
        refEntidade: 6
        presoTotal: presoTotal
        nome: nome
        id: 0
        refImagem: 5
        descricao: descricao
        pesoLiquido: pesoLiquido
      properties:
        id:
          format: int64
          type: integer
        nome:
          maxLength: 50
          minLength: 0
          nullable: true
          type: string
        refEntidade:
          format: int64
          nullable: true
          type: integer
        tipo:
          $ref: '#/components/schemas/TipoProduto'
        descricao:
          maxLength: 1000
          minLength: 0
          nullable: true
          type: string
        preco:
          format: double
          nullable: true
          type: number
        refImagem:
          format: int64
          nullable: true
          type: integer
        presoTotal:
          maxLength: 50
          minLength: 0
          nullable: true
          type: string
        pesoLiquido:
          maxLength: 50
          minLength: 0
          nullable: true
          type: string
        dimensoes:
          maxLength: 50
          minLength: 0
          nullable: true
          type: string
      type: object
    ProdutoDTOListResultado:
      additionalProperties: false
      example:
        ok: true
        message: message
        value:
        - preco: 1.4658129805029452
          dimensoes: dimensoes
          refEntidade: 6
          presoTotal: presoTotal
          nome: nome
          id: 0
          refImagem: 5
          descricao: descricao
          pesoLiquido: pesoLiquido
        - preco: 1.4658129805029452
          dimensoes: dimensoes
          refEntidade: 6
          presoTotal: presoTotal
          nome: nome
          id: 0
          refImagem: 5
          descricao: descricao
          pesoLiquido: pesoLiquido
      properties:
        ok:
          type: boolean
        message:
          nullable: true
          type: string
        value:
          items:
            $ref: '#/components/schemas/ProdutoDTO'
          nullable: true
          type: array
      type: object
    LocalDTO:
      additionalProperties: false
      example:
        refAssistencia: 6
        refReposicao: 5
        refGestorTecnico: 1
        latitude: latitude
        nome: nome
        id: 0
        refGestorReposicao: 5
        morada: morada
        longitude: longitude
      properties:
        id:
          format: int64
          type: integer
        nome:
          maxLength: 50
          minLength: 0
          nullable: true
          type: string
        morada:
          maxLength: 200
          minLength: 0
          nullable: true
          type: string
        refAssistencia:
          format: int64
          nullable: true
          type: integer
        refGestorTecnico:
          format: int64
          nullable: true
          type: integer
        refReposicao:
          format: int64
          nullable: true
          type: integer
        refGestorReposicao:
          format: int64
          nullable: true
          type: integer
        latitude:
          maxLength: 10
          minLength: 0
          nullable: true
          type: string
        longitude:
          maxLength: 10
          minLength: 0
          nullable: true
          type: string
      type: object
    LocalDTOListResultado:
      additionalProperties: false
      example:
        ok: true
        message: message
        value:
        - refAssistencia: 6
          refReposicao: 5
          refGestorTecnico: 1
          latitude: latitude
          nome: nome
          id: 0
          refGestorReposicao: 5
          morada: morada
          longitude: longitude
        - refAssistencia: 6
          refReposicao: 5
          refGestorTecnico: 1
          latitude: latitude
          nome: nome
          id: 0
          refGestorReposicao: 5
          morada: morada
          longitude: longitude
      properties:
        ok:
          type: boolean
        message:
          nullable: true
          type: string
        value:
          items:
            $ref: '#/components/schemas/LocalDTO'
          nullable: true
          type: array
      type: object
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      description: Please insert JWT token into field
      scheme: bearer
      type: http
